# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(max_length=255, verbose_name='Title')),
                ('gallery_image', models.ImageField(upload_to='images/gallery/', verbose_name='Image')),
                ('gallery_active', models.BooleanField(default=False, verbose_name='Active')),
                ('gallery_delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('gallery_created', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('gallery_modified', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
            ],
            options={
                'verbose_name': 'Gallery',
            },
        ),
    ]
