# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('gallery_title', models.CharField(max_length=255, verbose_name='Title')),
                ('gallery_image', models.ImageField(upload_to='images/gallery/', verbose_name='Image')),
                ('gallery_category', models.CharField(choices=[(b'general', b'General'), (b'news', b'News'), (b'events', b'Events')], max_length=50, verbose_name='Gallery Category')),
            ],
            options={
                'verbose_name': 'Gallery',
            },
        ),
    ]
