# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_delete_status',
            new_name='delete_status',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery_modified',
            new_name='modified_date',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_active',
        ),
        migrations.AddField(
            model_name='gallery',
            name='active_status',
            field=models.BooleanField(default=False, verbose_name='Active Status'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_category',
            field=models.CharField(choices=[(b'general', b'General'), (b'news', b'News'), (b'events', b'Events')], default=django.utils.timezone.now, max_length=50, verbose_name='Gallery Category'),
            preserve_default=False,
        ),
    ]
