# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.FileField(upload_to=gallery.models.update_image, verbose_name='Images'),
        ),
    ]
