# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_cateogry',
            field=models.CharField(choices=[(b'events', b'Events'), (b'news', b'News'), (b'shoutout', b'Shoutout')], max_length=50, verbose_name='Notification Category'),
        ),
    ]
