# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20180106_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_message',
            field=models.CharField(default=django.utils.timezone.now, help_text='It will be used only for CEO category', max_length=200, verbose_name='Notification Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_cateogry',
            field=models.CharField(choices=[(b'events', b'Events'), (b'news', b'News'), (b'shoutout', b'Shoutout'), (b'livetelecast', b'Livetelecast'), (b'birthday', b'Birthday'), (b'anniversary', b'Anniversary'), (b'ceo', b'CEO')], max_length=50, verbose_name='Notification Category'),
        ),
    ]
