# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20180106_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_message',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_cateogry_id',
            field=models.IntegerField(null=True, verbose_name='Notification Category Id'),
        ),
    ]
