# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20180108_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='ceo_message',
            field=models.CharField(max_length=200, unique=True, verbose_name='CEO message'),
        ),
    ]
