# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-08 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20180108_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceomessage',
            name='active_status',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
    ]
