# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livetelecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetelecast',
            name='livetelecast_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
