# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('events_title', models.CharField(max_length=255, verbose_name='Title')),
                ('events_description', models.TextField(max_length=1000, verbose_name='Description')),
                ('events_location_for_map', models.CharField(max_length=255, verbose_name='Location')),
                ('events_venue', models.CharField(max_length=255, verbose_name='Venue')),
                ('events_date', models.DateTimeField(verbose_name='Events Date')),
                ('events_image', models.ImageField(upload_to=events.models.update_image, verbose_name='Images')),
                ('events_video', models.FileField(upload_to=events.models.update_video, verbose_name='Video')),
                ('events_document', models.FileField(upload_to=events.models.update_file, verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Event',
            },
        ),
    ]
