# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='events_location',
            new_name='events_location_for_map',
        ),
        migrations.AlterField(
            model_name='events',
            name='active_status',
            field=models.BooleanField(default=False, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_date',
            field=models.DateTimeField(verbose_name='Events Date'),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_video',
            field=models.FileField(upload_to='video/events/', verbose_name='Video'),
        ),
    ]
