# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollsAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Polls Answer')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
            ],
        ),
        migrations.CreateModel(
            name='PollsQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('question', models.TextField(max_length=200, verbose_name='Polls question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('pollsresult_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollsAnswer', verbose_name='Answer')),
                ('pollsresult_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Employee')),
                ('pollsresult_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollsQuestion', verbose_name='Question')),
            ],
        ),
        migrations.AddField(
            model_name='pollsanswer',
            name='answer_questions',
            field=models.ManyToManyField(related_name='answers', to='polls.PollsQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='pollsresult',
            unique_together=set([('pollsresult_question', 'pollsresult_employee')]),
        ),
    ]
