# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_employee_email'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsanswer',
            name='answer_questions',
            field=models.ManyToManyField(related_name='answers', to='polls.PollsQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='pollsresult',
            unique_together=set([('pollsresult_question', 'pollsresult_employee')]),
        ),
    ]
