# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Gallery(models.Model):
	gallery_title = models.CharField(verbose_name = 'Title', max_length = 255)
	gallery_image = models.ImageField(verbose_name = 'Image', upload_to = 'images/gallery/')
	gallery_active = models.BooleanField(verbose_name = 'Active', default = False)
	gallery_delete_status = models.BooleanField(verbose_name = 'Delete status', default = False)
	gallery_created = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
	gallery_modified = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")

	def __str__(self):
		return self.gallery_title

	class Meta:
		verbose_name = "Gallery"
        verbose_name_plural = "Galleries"
        ordering = ['id']
