# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-10 09:41
from __future__ import unicode_literals

import banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.FileField(upload_to=banner.models.update_image, verbose_name='Banner Image'),
        ),
    ]
