# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_video',
            field=models.FileField(upload_to=b'', verbose_name='Video'),
        ),
    ]
