# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_document',
            field=models.FileField(blank=True, upload_to=news.models.update_file, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(upload_to=news.models.update_image, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_video',
            field=models.FileField(blank=True, upload_to=news.models.update_video, verbose_name='Video'),
        ),
    ]
