# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171206_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='active_status',
            field=models.BooleanField(default=False, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_video',
            field=models.FileField(upload_to='video/news/', verbose_name='Video'),
        ),
    ]
