# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 08:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active_status', models.BooleanField(default=False, verbose_name='Active Status')),
                ('delete_status', models.BooleanField(default=False, verbose_name='Delete status')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('modified_date', models.DateTimeField(auto_now_add=True, help_text='Auto generated by system.')),
                ('employee_id', models.CharField(max_length=15, verbose_name='Employee ID')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('employee_dob', models.DateField(verbose_name='Date of Birth')),
                ('employee_email', models.EmailField(max_length=255, verbose_name='Email ID')),
                ('employee_mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('employee_doj', models.DateField(verbose_name='Date of Joining')),
                ('employee_designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('employee_photo', models.ImageField(upload_to='images/profile/', verbose_name='Profile Image')),
                ('employee_bloodgroup', models.CharField(max_length=255, verbose_name='Blood Group')),
                ('employee_address', models.TextField(max_length=1000, verbose_name='Address')),
                ('employee_aadhar_id', models.PositiveIntegerField(verbose_name='Aadhar ID')),
                ('employee_experience_in_years', models.PositiveIntegerField(verbose_name='No. of Years experienced')),
                ('employee_device_id', models.CharField(max_length=255, verbose_name='Device Id')),
            ],
            options={
                'verbose_name': 'Employee',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
