# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_employeeId', models.PositiveIntegerField(verbose_name='Employee ID')),
                ('employee_employeeName', models.CharField(max_length=255, verbose_name='Employee Name')),
                ('employee_dateOfBirth', models.DateTimeField(verbose_name='Date of Birth')),
                ('employee_email', models.EmailField(max_length=255, verbose_name='Email ID')),
                ('employee_mobileNumber', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('employee_dateOfJoining', models.DateTimeField(verbose_name='Date of Joining')),
                ('employee_designation', models.CharField(max_length=255, verbose_name='Designation')),
                ('employee_photo', models.ImageField(upload_to='images/profile/', verbose_name='Profile pic')),
                ('employee_bloodGroup', models.CharField(max_length=255, verbose_name='Blood Group')),
                ('employee_address', models.TextField(max_length=1000, verbose_name='Address')),
                ('employee_aadharId', models.PositiveIntegerField(max_length=12, verbose_name='Aadhar ID')),
                ('employee_departmentId', models.CharField(max_length=255, verbose_name='Employee Department ID')),
                ('employee_experience', models.PositiveIntegerField(verbose_name='No. of Years experienced')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
