# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_aadhar_id',
            field=models.IntegerField(verbose_name='Aadhar ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_experience_in_years',
            field=models.IntegerField(verbose_name='No. of Years experienced'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='Employee ID'),
        ),
    ]
