# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-27 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_aadhar_id',
        ),
    ]
