# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

#Master model to use in throughout website
class AbstractDefault(models.Model):
	active_status = models.BooleanField(verbose_name = 'Active', default = False)
	delete_status = models.BooleanField(verbose_name = 'Delete status', default = False)
	created_date = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
	modified_date = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")

	class Meta:
		abstract = True

class Department(AbstractDefault):
	department_name = models.CharField(verbose_name = 'Department Name',max_length=50)

	def __str__(self):
		return self.department_name
