from __future__ import unicode_literals

from django.db import models
from master.models import AbstractDefault
from employee.models import Employee

class PollsQuestion(AbstractDefault):
	question = models.TextField(verbose_name = 'Polls question', max_length = 200)

	def __str__(self):
		return self.question

class PollsAnswer(models.Model):
	answer = models.CharField(verbose_name = 'Polls Answer', max_length = 100)
	answer_questions =models.ManyToManyField(PollsQuestion,related_name='answers')
	created_date = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
	modified_date = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")

	def get_questions(self):
		return "\n".join([p.question for p in self.answer_questions.all()])
		# get_questions.allow_tags = True
		# get_questions.short_description = 'quest'
		
	# def __str__(self):
	# 	return self.answer

class PollsResult(models.Model):
	pollsresult_employee = models.ForeignKey(Employee,verbose_name = 'Employee')
	pollsresult_question = models.ForeignKey(PollsQuestion,verbose_name = 'Question') 
	pollsresult_answer = models.ForeignKey(PollsAnswer,verbose_name = 'Answer') 
	created_date = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
	modified_date = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")

	def __str__(self):
		return self.id

	class Meta:
		unique_together = ("pollsresult_question","pollsresult_employee")



