# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-06 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_employee', to='employee.Employee', verbose_name='Employee'),
        ),
    ]
