# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_category_id',
            field=models.IntegerField(null=True, verbose_name='Aadhar ID'),
        ),
    ]
