# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-14 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20171214_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_queries',
            field=models.TextField(default=django.utils.timezone.now, max_length=500, verbose_name='Queries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_category_id',
            field=models.IntegerField(blank=True, help_text='It stores the events or news id', null=True, verbose_name='Category Id'),
        ),
    ]
