# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from embed_video.fields import EmbedVideoField

# Create your models here.

class AbstractDefault(models.Model):
	active = models.BooleanField(verbose_name = 'Active', default = False)
	delete_status = models.BooleanField(verbose_name = 'Delete status', default = False)
	created = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")
	modified = models.DateTimeField(auto_now_add=True, help_text="Auto generated by system.")

	class Meta:
		abstract = True
		
class News(AbstractDefault):
	news_title = models.CharField(verbose_name = 'Title', max_length = 255)
	news_description = models.TextField(verbose_name = 'Description', max_length = 1000)
	news_location = models.CharField(verbose_name = 'Location', max_length = 255)
	news_venue = models.CharField(verbose_name = 'Venue', max_length = 255)
	news_image = models.ImageField(verbose_name = 'Images', upload_to = 'images/news/')
	news_video = EmbedVideoField(verbose_name = 'Video') 
	news_document = models.FileField(verbose_name = 'Document', null = True, upload_to = 'files/news/')

	def __str__(self):
		return self.news_title

	class Meta:
		verbose_name = "New"
        verbose_name_plural = "News"
        ordering = ['id']

